# Generated by Django 4.1.6 on 2023-02-10 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='guardians',
            field=models.ManyToManyField(to='main_app.guardian'),
        ),
    ]
