# Generated by Django 4.1.6 on 2023-02-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_child_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='guardians',
        ),
        migrations.AddField(
            model_name='guardian',
            name='children',
            field=models.ManyToManyField(to='main_app.child'),
        ),
    ]
