# Generated by Django 4.1.6 on 2023-02-14 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_activity_assessment_feeding_attendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='assessment',
            name='child',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.child'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assessment',
            name='behavior',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
